-- Follows table for user follow system
CREATE TABLE IF NOT EXISTS public.follows (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  follower_id varchar NOT NULL,
  following_id varchar NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(follower_id, following_id),
  CHECK (follower_id <> following_id)
);

ALTER TABLE public.follows ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone view follows" ON public.follows FOR SELECT USING (true);
CREATE POLICY "Users follow others" ON public.follows FOR INSERT TO authenticated
  WITH CHECK ((auth.uid())::text = follower_id);
CREATE POLICY "Users unfollow" ON public.follows FOR DELETE TO authenticated
  USING ((auth.uid())::text = follower_id);

CREATE INDEX IF NOT EXISTS idx_follows_follower ON public.follows(follower_id);
CREATE INDEX IF NOT EXISTS idx_follows_following ON public.follows(following_id);

-- Notify on new follower
CREATE OR REPLACE FUNCTION public.notify_follow()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.notifications (user_id, type, title, body, link)
  VALUES (NEW.following_id, 'follow', '새 팔로워', '누군가 회원님을 팔로우했어요', '/users/' || NEW.follower_id);
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_notify_follow ON public.follows;
CREATE TRIGGER trg_notify_follow AFTER INSERT ON public.follows
FOR EACH ROW EXECUTE FUNCTION public.notify_follow();

-- Search history for advanced search
CREATE TABLE IF NOT EXISTS public.search_history (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id varchar NOT NULL,
  query varchar NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.search_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users view own search" ON public.search_history FOR SELECT TO authenticated
  USING ((auth.uid())::text = user_id);
CREATE POLICY "Users insert own search" ON public.search_history FOR INSERT TO authenticated
  WITH CHECK ((auth.uid())::text = user_id);
CREATE POLICY "Users delete own search" ON public.search_history FOR DELETE TO authenticated
  USING ((auth.uid())::text = user_id);

CREATE INDEX IF NOT EXISTS idx_search_history_user ON public.search_history(user_id, created_at DESC);

-- Reports table for admin dashboard
CREATE TABLE IF NOT EXISTS public.reports (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id varchar NOT NULL,
  target_type varchar NOT NULL,
  target_id varchar NOT NULL,
  reason text NOT NULL,
  status varchar NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users create reports" ON public.reports FOR INSERT TO authenticated
  WITH CHECK ((auth.uid())::text = reporter_id);
CREATE POLICY "Users view own reports" ON public.reports FOR SELECT TO authenticated
  USING ((auth.uid())::text = reporter_id OR is_admin(auth.uid()));
CREATE POLICY "Admins update reports" ON public.reports FOR UPDATE TO authenticated
  USING (is_admin(auth.uid())) WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "Admins delete reports" ON public.reports FOR DELETE TO authenticated
  USING (is_admin(auth.uid()));